### PR TITLE
don't subscribe when push/replace on a SrcArray

### PR DESCRIPTION
**Pull request by dodgejoel**
push doesn't feel like a listening event so it should not be

### CODE REVIEW

**Comment by rmehlinger** [comment]
This should be rebased and pulled into master.

**Comment by yang** [comment]
Merged

**Comment by dodgejoel** [comment]
Is this correct?  I do not see these changes when i pull and there is this warning message below this message thread . . . "Closed with unmerged commits
This pull request is closed, but the dodgejoel:length branch has unmerged commits."

**Comment by yang** [comment]
@dodgejoel Hmm, how are you checking?  Are you able to find this commit in
your checkout?
https://github.com/yang/reactive-coffee/commit/44be7c7d09acd8cdb1ccda62296873b96aa01e78

**Pull request closed without merging**
