### PR TITLE
Integrate Reactive SVG functionality #14

### PR DESCRIPTION
**Pull request by drernie**
This streamlines the patch from #14 by simply adding a list of SVG tags to the existing HTML tags.  I also added tests to verify they are added correctly, and ran the existing tests to make sure they didn't break anything.

To verify:
- create SVG elements (e.g., svg, rect)
- see that they are generated and display properly

### CODE REVIEW

**Comment by drernie** [comment]
Fixed the rendering bug, I believe.  Let me know what you hear.

**Comment by drernie** [comment]
Okay, the patch is not as elegant as I like, but it appears to work properly.  In this version I add all the SVG elements into rxt.svg_tags so as to not pollute the HTML rxt.tags.  In fact, it should behave identically for non-SVG elements, so this should be very low risk to integrate.

One side note:  to test this, I had to fix the JQuery dependency for node, including updating the package.json to include JQuery and Coffeeify.  Let me know if I should split that into a separate pull request.

Otherwise, I'd be happy to declare victory and move on. :-)

**Comment by yang** [comment]
Thanks @drernie!  Excited to merge this in, but do you know why the CI test is failing for the latest commit?

**Comment by drernie** [comment]
Ah, I didn't know about "npm test" -- I was only running "grunt test". Anything else I should be looking at?

**Comment by yang** [comment]
Hopefully that's it.  Thanks!

**Comment by drernie** [comment]
Okay, I know _where_ it is failing, though I don't yet understand why:

Near the bottom of reactive-coffee, I added JQuery support:

>  else if module?.exports?
>     $    = require 'jquery'
>     _    = require 'underscore'
>     rx = factory(_, $)
>     module.exports = rx

If I change the penultimate line to " rx = factory(_)", the test passes just fine (but then I don't get JQuery rxt tags on the server-side).  Any idea if there's a better way to do that?

**Comment by yang** [comment]
Might be best to separate out server-side rxt support, since that
introduces its own can of worms that I don't fully understand (unless you
know how to solve this :)....

**Comment by drernie** [comment]
One more issue that I've noticed, but am not sure how to test for or fix.  When I create certain elements (animate transform, use) the tags get generated in the DOM, but don't take effect. That is, they don't render on the dynamically-generated page, but if I save the resulting HTML they work fine.

 Not sure if this is related to the inability of JQuery to parse SVG elements (which I thought i worked around by special-casing SVG element creation).

**Comment by yang** [comment]
Sorry, can you provide an example?  I'm not sure what "animate transform,
use" means.  But anyway FWIW I do believe jQuery doesn't handle SVGs - I've
always had to use http://keith-wood.name/svg.html to make those two play
together.

**Comment by danielma** [comment]
@yang I am working with @drernie and he asked me to sort out the build issue 

I just pushed a commit that fixes the CI status.

The issue is that we are using reactive-coffee through [browserify](https://github.com/substack/node-browserify) which uses `module.exports` like server side node modules.

On the master branch, it is assumed that `module.exports` means that reactive coffee is being included server side. Therefore `rxt` is not available through browserify.

To fix this, @drernie added the `require('jquery')` line. This, however, broke `test/nodeTest.js` because the code inside the if block started at line 672 assumes a `window` object.  

To fix this, I have made it so reactive coffee only requires jQuery if it is being included in a browser

**Comment by yang** [comment]
Superb!  Sorry for the delay on this (holiday break) - huge thanks to @drernie and @danielma for pulling this together!  I look forward to playing with this closely over the next several days and ultimately staging a new release around this.

**Pull request merged**
